### ISSUE TITLE
Using datasette-jellyfish Plugin As the Basis for an OpenRefine Style Reconciliation Service

### ISSUE THREAD

**Issue by psychemedia** [simonw/datasette-jellyfish#1]
The OpenRefine application is widely used in Library Carpentry circles as a tool for cleaning dirty datasets.

Part of the OpenRefine system design included the definition of a [Reconciliation service API](https://github.com/OpenRefine/OpenRefine/wiki/Reconciliation-Service-API) based around a "reconciliation service" that would automate entity resolution for the contents of a data column within an OpenRefine project against a third party resolution service. Resolution essentially took the form of partial matching items to be resolved against known items and returning partial matches with a matched confidence score. Previously there have been some attempts to support simple services powered by CSV files (for example, [reconcile-csv (java)](http://okfnlabs.org/reconcile-csv/)  or [reconciliation_service_skeleton (py)](https://github.com/OpenRefine/reconciliation_service_skeleton)) but those examples appear to have rotted and/or been deprecated by updates to the reconciliation service API definition. There is also an [open issue](https://github.com/OpenRefine/OpenRefine/issues/2003) relating to how such a service may be implemented within OpenRefine itself.

Implementing such a service requires three things:

1) a canonical data source for matching against;
2) a fuzzy matching / scoring algorithm;
3) a service implementation of the OpenRefine reconciliation API.

The `jellyfish` plugin can be used to implement 2), so I wonder whether a plugin to implement the OpenRefine reconciliation service that can draw on this plugin would be useful?

The aim would be to provide a *simple* way for uses to define their own *datasette* powered reconciliation service that could then be called from OpenRefine, or elsewhere.

In the simplest case, a service could perhaps be started using something along the lines of:

`datasette-reconcile --canonical-data mysource.csv --search-column searchCol --id-col idCol --use-plugin datasette-jellyfish --scoring levenshtein_distance --port ${RECONCILE_SERVICE_PORT}`

**Comment by simonw** [comment]
@drkane is working on this over in https://github.com/drkane/datasette-reconcile !
